#!/usr/bin/env bash
# =============================================================================
# Samba Server Deployment Script
# Target OS  : Ubuntu 24.04 LTS
# Clients    : Windows 11, macOS (Time Machine), iPhone (Files app), Ubuntu 24
# Author     : Generated by Claude
# Usage      : sudo bash deploy_samba.sh
# =============================================================================

set -euo pipefail

# ─── Colour helpers ──────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; NC='\033[0m'
info()    { echo -e "${CYAN}[INFO]${NC}  $*"; }
success() { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
die()     { echo -e "${RED}[ERROR]${NC} $*" >&2; exit 1; }

# ─── Must run as root ────────────────────────────────────────────────────────
[[ $EUID -eq 0 ]] || die "Run this script with sudo or as root."

# =============================================================================
# CONFIGURATION  - edit these values before running
# =============================================================================
SAMBA_USER="sambauser"                       # Linux + Samba user
SAMBA_GROUP="smbgrp"                         # Samba access group
PUBLIC_DIR="/srv/samba/public"               # Read-only share (all smbgrp)
HOMES_DIR="/srv/samba/homes"                 # Per-user homes
TIMEMACHINE_DIR="/srv/samba/timemachine"     # Time Machine backup target
WORKGROUP="WORKGROUP"                        # Windows workgroup name
SERVER_STRING="Ubuntu Samba Server"
AVAHI_SERVICE_DIR="/etc/avahi/services"

# Prompt for the Samba (and Linux) password
read -rsp "Enter password for Samba user '${SAMBA_USER}': " SAMBA_PASS
echo
[[ -n "$SAMBA_PASS" ]] || die "Password cannot be empty."

# =============================================================================
# 1. INSTALL PACKAGES
# =============================================================================
info "Updating package index and installing Samba + Avahi + wsdd2…"
apt-get update -qq
apt-get install -y samba samba-common samba-common-bin \
        avahi-daemon avahi-utils \
        libnss-mdns wsdd2 acl attr ufw
success "Packages installed."

# =============================================================================
# 2. STOP SAMBA BEFORE CONFIGURATION
# =============================================================================
systemctl stop smbd nmbd wsdd2 2>/dev/null || true

# =============================================================================
# 3. CREATE GROUP AND USER
# =============================================================================
info "Creating group '${SAMBA_GROUP}'…"
getent group "${SAMBA_GROUP}" >/dev/null || groupadd "${SAMBA_GROUP}"

info "Creating Linux user '${SAMBA_USER}'…"
if ! id "${SAMBA_USER}" &>/dev/null; then
    useradd -m -s /bin/bash -G "${SAMBA_GROUP}" "${SAMBA_USER}"
else
    warn "User '${SAMBA_USER}' already exists - skipping creation."
    usermod -aG "${SAMBA_GROUP}" "${SAMBA_USER}"
fi

info "Setting Linux account password for '${SAMBA_USER}'…"
echo "${SAMBA_USER}:${SAMBA_PASS}" | chpasswd

info "Setting Samba password for '${SAMBA_USER}'…"
(echo "${SAMBA_PASS}"; echo "${SAMBA_PASS}") | smbpasswd -s -a "${SAMBA_USER}"
smbpasswd -e "${SAMBA_USER}"
success "User '${SAMBA_USER}' created and added to '${SAMBA_GROUP}'."

# =============================================================================
# 4. CREATE SHARE DIRECTORIES AND PERMISSIONS
# =============================================================================
info "Creating share directories…"
mkdir -p "${PUBLIC_DIR}" "${HOMES_DIR}/${SAMBA_USER}" "${TIMEMACHINE_DIR}"

# ── public ──────────────────────────────────────────────────────────────────
# smbgrp: read+execute; no write via Samba
chown root:"${SAMBA_GROUP}" "${PUBLIC_DIR}"
chmod 2750 "${PUBLIC_DIR}"                          # setgid; no world access
setfacl -m "g:${SAMBA_GROUP}:r-x" "${PUBLIC_DIR}"

# ── homes/sambauser ───────────────────────────────────────────────────────────
# sambauser: rw; rest of smbgrp: read-only
chown "${SAMBA_USER}":"${SAMBA_GROUP}" "${HOMES_DIR}/${SAMBA_USER}"
chmod 2750 "${HOMES_DIR}/${SAMBA_USER}"
setfacl -m "u:${SAMBA_USER}:rwx"  "${HOMES_DIR}/${SAMBA_USER}"
setfacl -m "g:${SAMBA_GROUP}:r-x" "${HOMES_DIR}/${SAMBA_USER}"

# ── timemachine ───────────────────────────────────────────────────────────────
# smbgrp: read+write
chown root:"${SAMBA_GROUP}" "${TIMEMACHINE_DIR}"
chmod 2770 "${TIMEMACHINE_DIR}"
setfacl -m "g:${SAMBA_GROUP}:rwx" "${TIMEMACHINE_DIR}"

success "Directories created and ACLs set."

# =============================================================================
# 5. WRITE smb.conf
# =============================================================================
info "Writing /etc/samba/smb.conf…"
SMB_CONF=/etc/samba/smb.conf
[[ -f "$SMB_CONF" ]] && cp "$SMB_CONF" "${SMB_CONF}.bak.$(date +%F_%T)"

cat > "$SMB_CONF" <<EOF
# =============================================================================
# Samba Configuration — Ubuntu 24.04
# Compatible: Windows 11 · macOS Time Machine · iPhone iOS Files
# =============================================================================

[global]
    workgroup             = ${WORKGROUP}
    netbios name          = $(hostname -s | tr '[:lower:]' '[:upper:]')
    server string         = ${SERVER_STRING}
    server role           = standalone server

    # ── Security (no guest access) ────────────────────────────────────────────
    security              = user
    map to guest          = Never
    guest ok              = no
    restrict anonymous    = 2

    # ── Protocol: SMB2/SMB3 only ──────────────────────────────────────────────
    # Required for Windows 11, macOS 13+, iOS 16+, Ubuntu 24
    server min protocol   = SMB2
    server max protocol   = SMB3

    # ── macOS/iOS compatibility via vfs_fruit ─────────────────────────────────
    vfs objects           = catia fruit streams_xattr
    fruit:metadata        = stream
    fruit:model           = MacSamba
    fruit:posix_rename    = yes
    fruit:veto_appledouble = no
    fruit:wipe_intentionally_left_blank_rfork = yes
    fruit:delete_empty_adfiles = yes

    # ── Disable printers ──────────────────────────────────────────────────────
    load printers         = no
    printing              = bsd
    printcap name         = /dev/null
    disable spoolss       = yes

    # ── Logging ───────────────────────────────────────────────────────────────
    log file              = /var/log/samba/log.%m
    log level             = 1
    max log size          = 1000

    # ── Performance ───────────────────────────────────────────────────────────
    socket options        = TCP_NODELAY IPTOS_LOWDELAY SO_RCVBUF=131072 SO_SNDBUF=131072
    read raw              = yes
    write raw             = yes
    oplocks               = yes
    max xmit              = 65535
    dead time             = 15

# =============================================================================
# SHARES
# =============================================================================

# ── public (read-only for all smbgrp members) ─────────────────────────────────
[public]
    comment               = Public - read-only for smbgrp
    path                  = ${PUBLIC_DIR}
    browseable            = yes
    guest ok              = no
    valid users           = @${SAMBA_GROUP}
    read only             = yes
    write list            =

# ── homes/sambauser (rw for owner, ro for group) ──────────────────────────────
[${SAMBA_USER}]
    comment               = Home of ${SAMBA_USER}
    path                  = ${HOMES_DIR}/${SAMBA_USER}
    browseable            = yes
    guest ok              = no
    valid users           = @${SAMBA_GROUP}
    read only             = yes
    write list            = ${SAMBA_USER}
    create mask           = 0640
    directory mask        = 2750
    force group           = ${SAMBA_GROUP}

# ── timemachine (rw for all smbgrp members) ───────────────────────────────────
[timemachine]
    comment               = Time Machine Backup
    path                  = ${TIMEMACHINE_DIR}
    browseable            = yes
    guest ok              = no
    valid users           = @${SAMBA_GROUP}
    read only             = no
    write list            = @${SAMBA_GROUP}
    create mask           = 0660
    directory mask        = 2770
    force group           = ${SAMBA_GROUP}

    # fruit Time Machine settings
    vfs objects           = catia fruit streams_xattr
    fruit:time machine    = yes
    fruit:time machine max size = 0    ; 0 = unlimited; change e.g. to 500G
EOF

success "smb.conf written."

# =============================================================================
# 6. AVAHI (mDNS / Bonjour) - auto-discovery for macOS & iPhone
# =============================================================================
info "Writing Avahi service definitions…"

cat > "${AVAHI_SERVICE_DIR}/samba.service" <<'AVAHISMB'
<?xml version="1.0" standalone='no'?>
<!DOCTYPE service-group SYSTEM "avahi-service.dtd">
<service-group>
  <name replace-wildcards="yes">%h</name>
  <service>
    <type>_smb._tcp</type>
    <port>445</port>
  </service>
  <service>
    <type>_device-info._tcp</type>
    <port>0</port>
    <txt-record>model=TimeCapsule8,119</txt-record>
  </service>
</service-group>
AVAHISMB

cat > "${AVAHI_SERVICE_DIR}/timemachine.service" <<'AVAHITM'
<?xml version="1.0" standalone='no'?>
<!DOCTYPE service-group SYSTEM "avahi-service.dtd">
<service-group>
  <name replace-wildcards="yes">%h Time Machine</name>
  <service>
    <type>_adisk._tcp</type>
    <port>9</port>
    <txt-record>sys=waMa=0,adVF=0x100</txt-record>
    <txt-record>dk0=adVF=0x82,adVN=timemachine,adVF=0x82</txt-record>
  </service>
</service-group>
AVAHITM

success "Avahi service files written."

# =============================================================================
# 7. WSDD2 - WS-Discovery (Windows 11 Network Neighbourhood)
# =============================================================================
info "Enabling wsdd2 for Windows 11 network discovery…"
systemctl enable wsdd2 --now 2>/dev/null \
    && success "wsdd2 enabled." \
    || warn "wsdd2 unit not found - install manually if needed."

# =============================================================================
# 8. VALIDATE smb.conf
# =============================================================================
info "Validating smb.conf…"
testparm -s "${SMB_CONF}" 2>&1 | grep -E "(Loaded|ERROR|WARNING)" || true

# =============================================================================
# 9. FIREWALL (UFW)
# =============================================================================
if command -v ufw &>/dev/null && ufw status | grep -q "Status: active"; then
    info "Adding UFW rules for Samba, mDNS, and WS-Discovery…"
    ufw allow 'Samba'       # 137,138/udp + 139,445/tcp
    ufw allow 5353/udp      # mDNS (Avahi / Bonjour)
    ufw allow 3702/udp      # WS-Discovery (wsdd2)
    success "UFW rules added."
else
    warn "UFW not active - ensure these ports are open on your firewall:"
    warn "  TCP 139, 445  |  UDP 137, 138, 5353, 3702"
fi

# =============================================================================
# 10. ENABLE & START SERVICES
# =============================================================================
info "Enabling and starting services…"
for svc in smbd nmbd avahi-daemon wsdd2; do
    systemctl enable "$svc"
    systemctl restart "$svc"
    if systemctl is-active --quiet "$svc"; then
        success "${svc} is running."
    else
        warn "${svc} failed to start - check: journalctl -u ${svc}"
    fi
done

# =============================================================================
# SUMMARY
# =============================================================================
HOSTNAME_VAL=$(hostname)
echo
echo -e "${GREEN}════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN} Samba deployment complete!${NC}"
echo -e "${GREEN}════════════════════════════════════════════════════════${NC}"
echo
echo -e "  Hostname    : ${CYAN}${HOSTNAME_VAL}${NC}"
echo -e "  Samba user  : ${CYAN}${SAMBA_USER}${NC}  (member of ${SAMBA_GROUP})"
echo
echo -e "  Shares:"
printf "    %-34s %s\n" "\\\\${HOSTNAME_VAL}\\public"      "read-only  (all smbgrp members)"
printf "    %-34s %s\n" "\\\\${HOSTNAME_VAL}\\${SAMBA_USER}" "rw for ${SAMBA_USER}, ro for rest of smbgrp"
printf "    %-34s %s\n" "\\\\${HOSTNAME_VAL}\\timemachine" "read-write (all smbgrp members)"
echo
echo -e "  Connection guides:"
echo -e "    Windows 11   → Explorer address bar : \\\\\\\\${HOSTNAME_VAL}"
echo -e "    macOS        → Finder ▸ Go ▸ Connect to Server : smb://${HOSTNAME_VAL}"
echo -e "    iPhone/iPad  → Files ▸ … ▸ Connect to Server  : smb://${HOSTNAME_VAL}"
echo -e "    Ubuntu 24    → Files ▸ Other Locations         : smb://${HOSTNAME_VAL}"
echo -e "    Time Machine → System Settings ▸ Time Machine ▸ Add Disk"
echo
echo -e "  Config backup  : ${SMB_CONF}.bak.*"
echo -e "${GREEN}════════════════════════════════════════════════════════${NC}"
